version: 2

models:
  - name: west_virginia_individual_contributions_transform
    description: >
      Transformed individual contribution data from West Virginia APOC reports,
    columns:
      - name: source
        description: Source system or state
        tests:
          - not_null
          - accepted_values:
              values: ['WV']

      - name: source_id
        description: ID for the contribution, prefixed with 'WV_'.
        tests:
          - not_null
          - unique
          - assert_has_prefix:
              prefix: WV_


      - name: committee_id
        description: Committee ID if applicable, ID for the contribution, prefixed with 'WV_'.
        tests:
          - not_null
          - assert_has_prefix:
              prefix: WV_

      - name: candidate_id
        description: Candidate ID if applicable, ID for the contribution, prefixed with 'WV_'.
        tests:
          - assert_has_prefix:
              prefix: WV_

      - name: candidate_name
        description: Candidate Name if applicable, ID for the contribution, prefixed with 'WV_'.

      - name: name
        description: Contributor name
        tests:
          - not_null

      - name: city
        description: Contributor city

      - name: state
        description: Contributor state

      - name: zip_code
        description: Contributor ZIP code

      - name: employer
        description: Contributor's employer

      - name: occupation
        description: Contributor's occupation

      - name: amount
        description: Contribution amount (numeric)
        tests:
          - not_null

      - name: contribution_datetime
        description: Timestamp when contribution was submitted
        tests:
          - not_null

      - name: insert_datetime
        description: When this record was inserted into the database
        tests:
          - not_null

  - name: west_virginia_committee_master_transform
    description: >
      Transformed West Virginia committee data mapped into the unified committee master schema.
      Each row represents a committee with normalized structure and a unique generated ID.
    columns:
      - name: source
        description: Static source identifier, 'WV' for West Virginia
        tests:
           - accepted_values:
              values: ['WV']

      - name: committee_id
        description: Generated unique ID for the committee using committee ID number
        tests:
          - not_null
          - unique
          - assert_has_prefix:
              prefix: WV_

      - name: committee_designation
        description: Placeholder for committee designation (currently null)

      - name: name
        description: Candidate or committee name
        tests:
          - not_null

      - name: address1
        description: Primary address line
        tests:
          - not_null

      - name: address2
        description: Secondary address line (currently null)

      - name: city
        description: City of the candidate or committee

      - name: state
        description: State or region (from state_region field)
        
      - name: zip_code
        description: ZIP code. It should have test not not_null due to extracting from address

      - name: affiliation
        description: Political affiliation/party

      - name: district
        description: Placeholder for district (currently null)
        
      - name: insert_datetime
        description: Timestamp of record insertion in UTC
        tests:
          - not_null

  - name: west_virginia_candidate_master_transform
    description: >
      Transformed West Virginia candidate data mapped into the unified candidate master schema.
      Each row represents a candidate with normalized structure and a unique generated ID.
    columns:
      - name: source
        description: Static source identifier, 'WV' for West Virginia
        tests:
          - accepted_values:
              values: ['WV']

      - name: candidate_id
        description: Generated unique ID for the candidate, prefixed with 'WV_'
        tests:
          - not_null
          - unique
          - assert_has_prefix:
              prefix: WV_

      - name: name
        description: Candidate name
        tests:
          - not_null

      - name: affiliation
        description: Political affiliation/party

      - name: election_year
        description: Year of the election

      - name: office_sought
        description: Office the candidate is running for

      - name: district
        description: District number or identifier

      - name: status
        description: Candidate status

      - name: finance_type
        description: Type of finance reporting

      - name: registration_date
        description: Date when candidate registered

      - name: treasurer_name
        description: Name of the campaign treasurer

      - name: address
        description: Candidate's address

      - name: phone_number
        description: Candidate's public phone number

      - name: committee_name
        description: Name of the political party committee

      - name: candidate_status
        description: Current status of the candidate

      - name: is_incumbent
        description: Whether the candidate is an incumbent

      - name: is_unregistered
        description: Whether the candidate is unregistered

      - name: cash_on_hand
        description: Cash on hand amount

      - name: total_contributions
        description: Total contributions received

      - name: total_expenditures
        description: Total expenditures made

      - name: insert_datetime
        description: Timestamp of record insertion in UTC
        tests:
          - not_null  