CREATE TABLE ma_committee_candidate_landing_table (
    "CPF ID" text,	
    "Account Type Code" text,	
    "Comm_Name" text,	
    "Is_Candidate_Only" text,
    "Candidate First Name" text,
    "Candidate Last Name" text,
    "Candidate Street Address" text,
    "Candidate City" text,	
    "Candidate State" text,	
    "Candidate Zip Code" text,
    "Treasurer First Name" text,
    "Treasurer Last Name" text,	
    "Comm Street Address" text,	
    "Comm City" text,
    "Comm State" text,
    "Comm Zip Code" text,	
    "Chair First Name" text,	
    "Chair Last Name" text,
    "Organization Date" text,	
    "District Code Sought" text,	
    "Office Type Sought" text,	
    "District Name Sought" text,
    "District Code Held" text,
    "Office Type Held" text,
    "District Name Held" text,
    "Related Candidate CPF ID" text,
    "Closed Date" text,	
    "Party Affiliation" text,
    "Unknown" text
);
