CREATE TABLE al_cash_contributions (
    org_id text,
    contribution_amount text,
    contribution_date text,
    last_name text,
    first_name text,
    mi text,
    suffix text,
    address1 text,
    city text,
    state text,
    zip text,
    contribution_id text,
    filed_date text,
    contribution_type text,
    contributor_type text,
    committee_type text,
    committee_name text,
    candidate_name text,
    amended text
);


CREATE TABLE al_expenditures (
    org_id text,
    expenditure_amount text,
    expenditure_date text,
    last_name text,
    first_name text,
    mi text,
    suffix text,
    address1 text,
    city text,
    state text,
    zip text,
    explanation text,
    expenditure_id text,
    filed_date text,
    purpose text,
    expenditure_type text,
    committee_type text,
    committee_name text,
    candidate_name text,
    amended text
);


CREATE TABLE al_in_kind_contributions (
    org_id text,
    contribution_amount text,
    contribution_date text,
    last_name text,
    first_name text,
    mi text,
    suffix text,
    address1 text,
    city text,
    state text,
    zip text,
    in_kind_contribution_id text,
    filed_date text,
    contribution_type text,
    contributor_type text,
    committee_type text,
    committee_name text,
    candidate_name text,
    amended text,
    nature_of_in_kind_contribution text
);


CREATE TABLE al_other_receipts (
    org_id text,
    receipt_amount text,
    receipt_date text,
    last_name text,
    first_name text,
    mi text,
    suffix text,
    address1 text,
    city text,
    state text,
    zip text,
    receipt_id text,
    filed_date text,
    receipt_type text,
    receipt_source_type text,
    committee_type text,
    committee_name text,
    candidate_name text,
    amended text,
    endorser_name1 text,
    endorser_address1 text,
    endorser_guaranteed_amt1 text,
    endorser_name2 text,
    endorser_address2 text,
    endorser_guaranteed_amt2 text,
    endorser_name3 text,
    endorser_address3 text,
    endorser_guaranteed_amt3 text
);
