
CREATE TABLE vermont_candidates_landing (
    filing_entity_id TEXT,
    candidate_last_name TEXT,
    candidate_first_name TEXT,
    candidate_middle_name TEXT,
    candidate_address_line1 TEXT,
    candidate_address_line2 TEXT,
    candidate_city TEXT,
    candidate_state TEXT,
    candidate_zip_code TEXT,
    candidate_email TEXT,
    candidate_phone TEXT,
    candidate_website TEXT,
    office_type TEXT,
    office TEXT,
    town_or_city TEXT,
    total_contributions TEXT,
    total_expenditures TEXT,
    election_cycle TEXT,
    account_status TEXT,
    treasurer_last_name TEXT,
    treasurer_first_name TEXT,
    treasurer_middle_name TEXT,
    treasurer_email TEXT,
    treasurer_phone TEXT,
    treasurer_address_line1 TEXT,
    treasurer_address_line2 TEXT,
    treasurer_city TEXT,
    treasurer_state TEXT,
    treasurer_zip_code TEXT,
    name_of_financial_institution TEXT,
    name_of_financial_institution_address_line1 TEXT,
    name_of_financial_institution_address_line2 TEXT,
    name_of_financial_institution_city TEXT,
    name_of_financial_institution_state TEXT,
    name_of_financial_institution_zip_code TEXT
);


CREATE TABLE vermont_committees_landing (
    filing_entity_id TEXT,
    committee_name TEXT,
    abbreviated_committee_name TEXT,
    committee_type TEXT,
    committee_sub_type TEXT,
    committee_address TEXT,
    committee_website TEXT,
    treasurer_last_name TEXT,
    treasurer_first_name TEXT,
    financial_institution_name TEXT,
    total_contributions TEXT,
    total_expenditure TEXT,
    election_cycle TEXT,
    account_status TEXT,
    town TEXT,
    public_question TEXT,
    stance TEXT
);
