-- Georgia Contributions and Loans Landing table
CREATE TABLE ga_contributions_and_loans_landing (
    "Filer_ID" text,
    "Transaction_Amount" text,
    "Transaction_Date" text,
    "Last_Name" text,
    "First_Name" text,
    "Middle_Name" text,
    "Prefix" text,
    "Suffix" text,
    "Contributor_Address_Line_1" text,
    "Contributor_Address_Line_2" text,
    "Contributor_City" text,
    "Contributor_State" text,
    "Contributor_Zip_Code" text,
    "Description" text,
    "Check_Number" text,
    "Transaction_ID" text,
    "Filed_Date" text,
    "Election" text,
    "Report_Name" text,
    "Start_of_Period" text,
    "End_of_Period" text,
    "Contributor_Code" text,
    "Contribution_Type" text,
    "Report_Entity_Type" text,
    "Committee_Name" text,
    "Candidate_Last_Name" text,
    "Candidate_First_Name" text,
    "Candidate_Middle_Name" text,
    "Candidate_Prefix" text,
    "Candidate_Suffix" text,
    "Amended" text,
    "Contributor_Employer" text,
    "Contributor_Occupation" text,
    "Occupation_Comment" text,
    "Employment_Information_Requested" text
);

-- Georgia Expenditures Landing Table
CREATE TABLE ga_expenditures_landing (
    "Filer_ID" text,
    "Expenditure_Amount" text,
    "Expenditure_Date" text,
    "Payee_Last_Name" text,
    "Payee_First_Name" text,
    "Payee_Middle_Name" text,
    "Payee_Prefix" text,
    "Payee_Suffix" text,
    "Payee_Address_1" text,
    "Payee_Address_2" text,
    "Payee_City" text,
    "Payee_State" text,
    "Payee_Zip_Code" text,
    "Description" text,
    "Expenditure_ID" text,
    "Filed_Date" text,
    "Election" text,
    "Report_Name" text,
    "Start_of_Period" text,
    "End_of_Period" text,
    "Purpose" text,
    "Expenditure_Type" text,
    "Reason" text,
    "Stance" text,
    "Report_Entity_Type" text,
    "Committee_Name" text,
    "Candidate_Last_Name" text,
    "Candidate_First_Name" text,
    "Candidate_Middle_Name" text,
    "Candidate_Prefix" text,
    "Candidate_Suffix" text,
    "Amended" text
);
