CREATE TABLE ak_all_candidates_landing (
    result TEXT,
    "year" TEXT,
    candidate TEXT,
    candidate_email TEXT,
    address TEXT,
    city TEXT,
    state_region TEXT,
    zip TEXT,
    country TEXT,
    office TEXT,
    election TEXT,
    source TEXT,
    won TEXT,
    status TEXT,
    party TEXT,
    treasurer TEXT,
    treasurer_email TEXT,
    chair TEXT,
    chair_email TEXT,
    initial_filing TEXT
);

CREATE TABLE ak_campaign_disclosure_form_landing (
    result TEXT,
    report_year TEXT,
    report_type TEXT,
    begin_date TEXT,
    end_date TEXT,
    filer_type TEXT,
    name TEXT,
    beginning_cash_on_hand TEXT,
    total_income TEXT,
    previous_campaign_income TEXT,
    campaign_income_total TEXT,
    total_expenditures TEXT,
    previous_campaign_expense TEXT,
    campaign_expense_total TEXT,
    closing_cash_on_hand TEXT,
    total_debt TEXT,
    surplus_deficit TEXT,
    submitted TEXT,
    status TEXT,
    amending TEXT
);

CREATE TABLE ak_campaign_disclosure_income_landing (
    result TEXT,
    date TEXT,
    transaction_type TEXT,
    payment_type TEXT,
    payment_detail TEXT,
    amount TEXT,
    last_business_name TEXT,
    first_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    country TEXT,
    occupation TEXT,
    employer TEXT,
    purpose_of_expenditure TEXT,
    placeholder TEXT,
    report_type TEXT,
    election_name TEXT,
    election_type TEXT,
    municipality TEXT,
    office TEXT,
    filer_type TEXT,
    name TEXT,
    report_year TEXT,
    submitted TEXT
);

CREATE TABLE ak_campaign_disclosure_expenditures_landing (
    result TEXT,
    date TEXT,
    transaction_type TEXT,
    payment_type TEXT,
    payment_detail TEXT,
    amount TEXT,
    last_business_name TEXT,
    first_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    country TEXT,
    occupation TEXT,
    employer TEXT,
    purpose_of_expenditure TEXT,
    placeholder TEXT,
    report_type TEXT,
    election_name TEXT,
    election_type TEXT,
    municipality TEXT,
    office TEXT,
    filer_type TEXT,
    name TEXT,
    report_year TEXT,
    submitted TEXT
);

CREATE TABLE ak_campaign_disclosure_transactions_landing (
    result TEXT,
    date TEXT,
    transaction_type TEXT,
    payment_type TEXT,
    payment_detail TEXT,
    amount TEXT,
    last_business_name TEXT,
    first_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    country TEXT,
    occupation TEXT,
    employer TEXT,
    purpose_of_expenditure TEXT,
    placeholder_column TEXT,
    report_type TEXT,
    election_name TEXT,
    election_type TEXT,
    municipality TEXT,
    office TEXT,
    filer_type TEXT,
    name TEXT,
    report_year TEXT,
    submitted TEXT
);

CREATE TABLE ak_campaign_disclosure_debt_landing (
    result TEXT,
    date TEXT,
    balance_remaining TEXT,
    original_amount TEXT,
    name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    country TEXT,
    description_purpose TEXT,
    placeholder_column TEXT,
    filer_type TEXT,
    name_2 TEXT,
    report_year TEXT,
    submitted TEXT
);
