CREATE TABLE ak_contribution_reports_landing (
    result TEXT,
    report_year TEXT,
    filing_reason TEXT,
    filer_type TEXT,
    filer_name TEXT,
    filer_address TEXT,
    filer_city TEXT,
    filer_state TEXT,
    filer_zip TEXT,
    filer_country TEXT,
    business_type TEXT,
    email TEXT,
    phone TEXT,
    occupation TEXT,
    employer TEXT,
    total_contributed_this_report TEXT,
    total_contributed_this_year TEXT,
    submitted TEXT,
    status TEXT,
    separator TEXT,
    contribution_count TEXT,
    contact_first_name TEXT,
    contact_last_name TEXT,
    contact_email TEXT,
    contact_phone TEXT
);
