CREATE TABLE ok_contributions_loans_landing (
    receipt_id TEXT,
    org_id TEXT,
    receipt_type TEXT,
    receipt_date TEXT,
    receipt_amount TEXT,
    description TEXT,
    receipt_source_type TEXT,
    last_name TEXT,
    first_name TEXT,
    middle_name TEXT,
    suffix TEXT,
    address_1 TEXT,
    address_2 TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    filed_date TEXT,
    committee_type TEXT,
    committee_name TEXT,
    candidate_name TEXT,
    amended TEXT,
    employer TEXT,
    occupation TEXT,
    row_count INT
);

CREATE TABLE ok_expenditures_landing (
    expenditure_id TEXT,
    org_id TEXT,
    expenditure_type TEXT,
    expenditure_date TEXT,
    expenditure_amount TEXT,
    description TEXT,
    purpose TEXT,
    last_name TEXT,
    first_name TEXT,
    middle_name TEXT,
    suffix TEXT,
    address_1 TEXT,
    address_2 TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    filed_date TEXT,
    committee_type TEXT,
    committee_name TEXT,
    candidate_name TEXT,
    amended TEXT,
    employer TEXT,
    occupation TEXT
);

CREATE TABLE ok_lobbyist_expenditures_landing (
    expenditure_id TEXT,
    lobbyist_id TEXT,
    lobbyist_first_name TEXT,
    lobbyist_middle_name TEXT,
    lobbyist_last_name TEXT,
    lobbyist_suffix TEXT,
    expenditure_type TEXT,
    expenditure_date TEXT,
    expenditure_cost TEXT,
    meal_type TEXT,
    other_meal_description TEXT,
    explanation TEXT,
    recipient_first_name TEXT,
    recipient_middle_name TEXT,
    recipient_last_name TEXT,
    recipient_suffix TEXT,
    recipient_type TEXT,
    recipient_title TEXT,
    recipient_agency_office TEXT,
    relationship_to_state_officer_or_employee TEXT,
    family_member_name TEXT,
    principal_name TEXT,
    principals_percentage_cost TEXT,
    caucus TEXT,
    committee_subcommittee TEXT,
    event_location TEXT,
    event_city TEXT,
    event_state TEXT,
    row_count TEXT
);
