CREATE TABLE hi_contrib_made_to_candidate_landing_table (
    "Noncandidate Committee Name" text,
    "Candidate Name" text,
    "CC Reg No" text,
    "Candidate Committee Name" text,
    "Date" text,
    "Amount" text,
    "Aggregate" text,
    "Address 1" text,
    "Address 2" text,
    "City" text,
    "State" text,
    "Zip Code" text,
    "Non-Monetary (Yes or No)" text,
    "Non-Monetary Category" text,
    "Non-Monetary Description" text,
    "Reg No" text,
    "Election Period" text,
    "Mapping Location" text,
    "Office" text,
    "District" text,
    "County" text,
    "Party" text
);

CREATE TABLE hi_contrib_recv_by_candidate_landing_table (
    "Candidate Name" text,
    "Contributor Type" text,
    "Contributor Name" text,
    "Date" text,
    "Amount" text,
    "Aggregate" text,
    "Employer" text,
    "Occupation" text,
    "Address 1" text,
    "Address 2" text,
    "City" text,
    "State" text,
    "Zip Code" text,
    "Non-Resident (Yes or No)" text,
    "Non-Monetary (Yes or No)" text,
    "Non-Monetary Category" text,
    "Non-Monetary Description" text,
    "Office" text,
    "District" text,
    "County" text,
    "Party" text,
    "Reg No" text,
    "Election Period" text,
    "Mapping Location" text,
    "InOutState" text,
    "Range" text
);

CREATE TABLE hi_contrib_recv_by_non_candidates_landing_table (
    "Noncandidate Committee Name" text,
    "Contributor Type" text,
    "Contributor Name" text,
    "Date" text,
    "Amount" text,
    "Aggregate" text,
    "Employer" text,
    "Occupation" text,
    "Address 1" text,
    "Address 2" text,
    "City" text,
    "State" text,
    "Zip Code" text,
    "Non-Monetary (Yes or No)" text,
    "Non-Monetary Category" text,
    "Non-Monetary Description" text,
    "Reg No" text,
    "Election Period" text,
    "Mapping Location" text
);

CREATE TABLE hi_expenditure_made_by_candidate_landing_table (
    "Candidate Name" text,
    "Vendor Type" text,
    "Vendor Name" text,
    "Date" text,
    "Amount" text,
    "Authorized Use" text,
    "Expenditure Category" text,
    "Purpose of Expenditure" text,
    "Address 1" text,
    "Address 2" text,
    "City" text,
    "State" text,
    "Zip Code" text,
    "Office" text,
    "District" text,
    "County" text,
    "Party" text,
    "Reg No" text,
    "Election Period" text,
    "Mapping Location" text,
    "InOutState" text
);

CREATE TABLE hi_expenditure_made_by_non_candidate_landing_table (
    "Noncandidate Committee Name" text,
    "Vendor Type" text,
    "Vendor Name" text,
    "Date" text,
    "Amount" text,
    "Expenditure Category" text,
    "Purpose of Expenditure" text,
    "Independent Expenditure" text,
    "Candidate Name(s)" text,
    "Support/Oppose" text,
    "Address 1" text,
    "Address 2" text,
    "City" text,
    "State" text,
    "Zip Code" text,
    "Reg No" text,
    "Election Period" text,
    "Mapping Location" text
);

CREATE TABLE hi_loans_recv_by_candidate_landing_table (
    "Candidate Name" text,
    "Lender Type" text,
    "Lender Name" text,
    "Date" text,
    "Loan Amount" text,
    "Loan Type" text,
    "Loan Source" text,
    "Purpose of Loan" text,
    "Repay Amount" text,
    "Loan ID" text,
    "Forgiven" text,
    "Address 1" text,
    "Address 2" text,
    "City" text,
    "State" text,
    "Zip Code" text,
    "Office" text,
    "District" text,
    "County" text,
    "Party" text,
    "Reg No" text,
    "Election Period" text,
    "Mapping Location" text
);