
CREATE TABLE ky_organizations_landing (
    organization_name text,
    organization_type text,
    candidate_first_name text,
    candidate_last_name text,
    political_issue_amendment_or_question text,
    political_view text,
    office_sought text,
    location text,
    election_date text,
    election_type text,
    chair_name text,
    chair_address1 text,
    chair_address2 text,
    chair_city text,
    chair_state text,
    chair_phone text,
    treasurer_name text,
    treasurer_address1 text,
    treasurer_address2 text,
    treasurer_city text,
    treasurer_state text,
    treasurer_phone text,
    contact_name text,
    contact_address1 text,
    contact_address2 text,
    contact_city text,
    contact_state text,
    contact_phone text,
    is_active_label text
)