CREATE TABLE nc_transactions_landing (
    "Name" text,
    "StreetLine1" text,
    "StreetLine2" text,
    "City" text,
    "State" text,
    "ZipCode" text,
    "ProfessionOrJobTitle" text,
    "EmployersNameOrSpecificField" text,
    "TransctionType" text,
    "CommitteeName" text,
    "CommitteeSBoEID" text,
    "CommitteeStreet1" text,
    "CommitteeStreet2" text,
    "CommitteeCity" text,
    "CommitteeState" text,
    "CommitteeZipCode" text,
    "ReportName" text,
    "DateOccured" text,
    "AccountCode" text,
    "Amount" text,
    "FormofPayment" text,
    "Purpose" text,
    "CandidateOrReferendumName" text,
    "Declaration" text
);
