CREATE TABLE mn_contrib_landing_table (
    "Recipient reg num" text,
    "Recipient" text,
    "Recipient type" text,
    "Recipient subtype" text,
    "Amount" text,
    "Receipt date" text,
    "Year" text,
    "Contributor" text,
    "Contrib Reg Num" text,
    "Contrib type" text,
    "Receipt type" text,
    "In kind?" text,
    "In-kind descr" text,
    "Contrib zip" text,
    "Contrib Employer name" text
);

CREATE TABLE mn_general_expenditures_landing_table (
    "Committee reg num" text,
    "Committee name" text,
    "Entity type" text,
    "Entity sub-type" text,
    "Vendor name" text,
    "Vendor address 1" text,
    "Vendor address 2" text,
    "Vendor city" text,
    "Vendor state" text,
    "Vendor zip" text,
    "Amount" text,
    "Unpaid amount" text,
    "Date" text,
    "Purpose" text,
    "Year" text,
    "Type" text,
    "In-kind descr" text,
    "In-kind?" text,
    "Affected committee name" text,
    "Affected committee reg num" text
);

CREATE TABLE mn_independent_expenditures_landing_table (
    "Spender" text,
    "Spender Reg Num" text,
    "Spender type" text,
    "Spender sub-type" text,
    "Affected Comte Name" text,
    "Affected Cmte Reg Num" text,
    "For /Against" text,
    "Year" text,
    "Date" text,
    "Type" text,
    "Amount" text,
    "Unpaid amount" text,
    "In kind?" text,
    "In kind descr" text,
    "Purpose" text,
    "Vendor name" text,
    "Vendor address 1" text,
    "Vendor address 2" text,
    "Vendor city" text,
    "Vendor State" text,
    "Vendor zip" text
)