-- Create Michigan contributions landing table
CREATE TABLE mi_contributions_landing (
    doc_seq_no TEXT,
    page_no TEXT,
    contribution_id TEXT,
    cont_detail_id TEXT,
    doc_stmnt_year TEXT,
    doc_type_desc TEXT,
    com_legal_name TEXT,
    common_name TEXT,
    cfr_com_id TEXT,
    com_type TEXT,
    can_first_name TEXT,
    can_last_name TEXT,
    contribtype TEXT,
    f_name TEXT,
    l_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    occupation TEXT,
    employer TEXT,
    received_date TEXT,
    amount TEXT,
    aggregate TEXT,
    extra_desc TEXT,
    runtime TEXT
);
