CREATE TABLE or_committees_landing (
    "CommitteeId" TEXT,
    "CommitteeName" TEXT,
    "CommitteeType" TEXT,
    "CommitteeSubType" TEXT,
    "CandidateOffice" TEXT,
    "CandidateOfficeGroup" TEXT,
    "FilingDate" TEXT,
    "OrganizationFilingDate" TEXT,
    "TreasurerFirstName" TEXT,
    "TreasurerLastName" TEXT,
    "TreasurerMailingAddress" TEXT,
    "TreasurerWorkPhone" TEXT,
    "TreasurerFax" TEXT,
    "CandidateFirstName" TEXT,
    "CandidateLastName" TEXT,
    "CandidateMalingAddress" TEXT,
    "CandidateWorkPhone" TEXT,
    "CandidateResidencePhone" TEXT,
    "CandidateFax" TEXT,
    "CandidateEmail" TEXT,
    "ActiveElection" TEXT,
    "Measure" TEXT
);
