CREATE TABLE nh_candidates_landing (
    "filerName"  TEXT,
    "officeSoughtName"  TEXT,
    "town"  TEXT,
    "committeeName"  TEXT,
    "totalRaised"  TEXT,
    "totalSpent"  TEXT,
    "electionYear"  TEXT,
    "filerStatus"  TEXT,
    "filerTypeCode"  TEXT,
    "filerTypeDesc"  TEXT,
    "filerSubtypeName"  TEXT,
    "committeeMakingIE"  TEXT,
    "politicalParty"  TEXT,
    "guid"  TEXT,
    "officeTypeDesc"  TEXT,
    "filerStatusCode"  TEXT,
    "electionCycle"  TEXT,
    "isPaperFiler"  TEXT,
    "totalRows"  TEXT
);

CREATE TABLE nh_receipts_landing (
    "transactionID"  TEXT,
    "guid"  TEXT,
    "filerName"  TEXT,
    "filerRegistrationGuid"  TEXT,
    "transactionSubType"  TEXT,
    "transactionSource"  TEXT,
    "transactionDate"  TEXT,
    "transactionAmount"  TEXT,
    "electionType"  TEXT,
    "sourceName"  TEXT,
    "totalTransactionToTheFiler"  TEXT,
    "isAmended"  TEXT,
    "reportName"  TEXT,
    "reportVersion"  TEXT,
    "transactionTypeDesc"  TEXT,
    "timedReport"  TEXT,
    "timedReportCode"  TEXT,
    "hasChild"  TEXT,
    "reportVersionFilter"  TEXT,
    "registrationType"  TEXT,
    "filerReportGuid"  TEXT,
    "timedFiledReportGuid"  TEXT,
    "electionCycle"  TEXT,
    "totalRows"  TEXT
);

CREATE TABLE nh_expenditure_landing (
    "transactionID"  TEXT,
    "guid"  TEXT,
    "filerName"  TEXT,
    "transactionAmount"  TEXT,
    "transactionDate"  TEXT,
    "sourceName"  TEXT,
    "transactionSource"  TEXT,
    "reportName"  TEXT,
    "transactionSubType"  TEXT,
    "hasChild"  TEXT,
    "filerRegistrationGuid"  TEXT,
    "transactionCategory"  TEXT,
    "electionType"  TEXT,
    "isAmended"  TEXT,
    "transactionTypeDesc"  TEXT,
    "reportVersion"  TEXT,
    "stance"  TEXT,
    "candidateMeasure"  TEXT,
    "registrationType"  TEXT,
    "filerReportGuid"  TEXT,
    "timedFiledReportGuid"  TEXT,
    "timedReport"  TEXT,
    "electionCycle"  TEXT,
    "totalRows" TEXT
);

CREATE TABLE nh_loans_received_landing (
    "transactionID"  TEXT,
    "filerName"  TEXT,
    "filerRegistrationGuid"  TEXT,
    "outStandingBalance"  TEXT,
    "transactionDate"  TEXT,
    "sourceName"  TEXT,
    "reportName"  TEXT,
    "guid"  TEXT,
    "hasChild"  TEXT,
    "amended"  TEXT,
    "electionYear"  TEXT,
    "electionCycleYear"  TEXT,
    "electionPeriod"  TEXT,
    "transactionSourceType"  TEXT,
    "transactionAmount"  TEXT,
    "reportVersion"  TEXT,
    "filerReportGuid"  TEXT,
    "timedReport"  TEXT,
    "timedFiledReportGuid"  TEXT,
    "electionCycle"  TEXT,
    "totalRows" TEXT
);

CREATE TABLE nh_filings_and_reports_landing (
    "reportName"  TEXT,
    "filePath"  TEXT,
    "startDate"  TEXT,
    "endDate"  TEXT,
    "dueDate"  TEXT,
    "filedDate"  TEXT,
    "filerName"  TEXT,
    "filerType"  TEXT,
    "officeName"  TEXT,
    "reportType"  TEXT,
    "reportStatus"  TEXT,
    "filerEntityID"  TEXT,
    "filerEntityVersID"  TEXT,
    "filerReportGuid"  TEXT,
    "filerFilingCalendarGuid"  TEXT,
    "filerRegistrationGuid"  TEXT,
    "reportVersion"  TEXT,
    "filerReportVersionId"  TEXT,
    "hasChild"  TEXT,
    "isPaperFile"  TEXT,
    "filerSubtypeName"  TEXT,
    "filerSubtypeCode"  TEXT,
    "noActivityReport"  TEXT,
    "electionCycle"  TEXT,
    "totalRows"  TEXT
);