CREATE TABLE ar_candidates_landing (
    filer_name TEXT,
    office TEXT,
    office_district_name TEXT,
    filer_entity_version_id TEXT,
    filer_entity_id TEXT,
    filer_type TEXT,
    political_party TEXT,
    filer_status TEXT,
    total_raised TEXT,
    total_spent TEXT,
    balance_of_funds TEXT,
    election_year TEXT,
    guid TEXT,
    filer_type_code TEXT,
    filer_type_desc TEXT,
    filing_year TEXT,
    committee_name TEXT,
    first_name TEXT,
    last_name TEXT,
    suffix TEXT,
    balance_of_funds_new TEXT,
    total_raised_new TEXT,
    total_spent_new TEXT,
    filing_type_code TEXT,
    is_paper_filer TEXT,
    total_rows TEXT
);

CREATE TABLE ar_commitees_landing (
    "filerName" TEXT,
    "office" TEXT,
    "officeDistrictName" TEXT,
    "filerEntityVersionID" TEXT,
    "filerEntityID" TEXT,
    "filerType" TEXT,
    "politicalParty" TEXT,
    "filerStatus" TEXT,
    "totalRaised" TEXT,
    "totalSpent" TEXT,
    "balanceofFunds" TEXT,
    "electionYear" TEXT,
    "guid" TEXT,
    "filerTypeCode" TEXT,
    "filerTypeDesc" TEXT,
    "filingYear" TEXT,
    "committeeName" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "suffix" TEXT,
    "balanceofFundsNew" TEXT,
    "totalRaisedNew" TEXT,
    "totalSpentNew" TEXT,
    "filingTypeCode" TEXT,
    "isPaperFiler" TEXT,
    "totalRows" TEXT
);

CREATE TABLE ar_contributions_landing (
    guid TEXT,
    filer_name TEXT,
    transaction_amount TEXT,
    transaction_date TEXT,
    source_name TEXT,
    employer_name TEXT,
    occupation TEXT,
    source_address TEXT,
    transaction_source TEXT,
    report_name TEXT,
    transaction_sub_type_desc TEXT,
    has_child TEXT,
    filer_registration_guid TEXT,
    transaction_category TEXT,
    total_rows TEXT
);

CREATE TABLE ar_expenditures_landing (
    guid TEXT,
    filer_name TEXT,
    transaction_amount TEXT,
    transaction_date TEXT,
    source_name TEXT,
    employer_name TEXT,
    occupation TEXT,
    source_address TEXT,
    transaction_source TEXT,
    report_name TEXT,
    transaction_sub_type_desc TEXT,
    has_child TEXT,
    filer_registration_guid TEXT,
    transaction_category TEXT,
    total_rows TEXT
);

CREATE TABLE ar_loans_debts_landing (
    filer_guid TEXT,
    transaction_id TEXT,
    filer_name TEXT,
    filer_entity_id TEXT,
    filer_registration_id TEXT,
    filer_registration_guid TEXT,
    transaction_amount TEXT,
    balance_amount TEXT,
    transaction_date TEXT,
    source_name TEXT,
    employer_name TEXT,
    occupation TEXT,
    source_address TEXT,
    transaction_source TEXT,
    transaction_type_code TEXT,
    transaction_type_desc TEXT,
    report_name TEXT,
    guarantor TEXT,
    page_number TEXT,
    page_size TEXT,
    guid TEXT,
    transaction_sub_type_desc TEXT,
    filer_type_code TEXT,
    filer_type_desc TEXT,
    has_child TEXT,
    new_transaction_amount TEXT,
    new_balance_amount TEXT,
    new_transaction_date TEXT,
    total_rows TEXT
);

CREATE TABLE ar_fillings_and_reports_landing (
    report_name TEXT,
    file_path TEXT,
    start_date TEXT,
    end_date TEXT,
    due_date TEXT,
    filed_date TEXT,
    filer_name TEXT,
    filer_type TEXT,
    office_name TEXT,
    report_type TEXT,
    report_status TEXT,
    filer_entity_id TEXT,
    filer_entity_vers_id TEXT,
    filer_report_guid TEXT,
    filer_filing_calendar_guid TEXT,
    filer_registration_guid TEXT,
    report_version TEXT,
    filer_report_version_id TEXT,
    has_child TEXT,
    is_paper_file TEXT,
    total_rows TEXT
);

CREATE TABLE ar_legacy_filled_reports_landing (
    filer_name TEXT,
    file_name TEXT,
    report_type TEXT,
    filer_type TEXT,
    office_type TEXT,
    registration_year TEXT,
    filed_date TEXT,
    filer_registration_guid TEXT,
    legacy_filer_registration_id TEXT,
    total_rows TEXT,
    filer_type_code TEXT,
    max_filed_date TEXT,
    min_filed_date TEXT,
    report_start_date TEXT,
    report_end_date TEXT,
    report_due_date TEXT,
    report_version TEXT,
    filer_report_guid TEXT,
    id TEXT,
    file_path TEXT
);
--
