CREATE TABLE ia_campaign_contributions_received_landing (
    "date" TEXT,
    committee_code TEXT,
    committee_type TEXT,
    committee_name TEXT,
    transaction_type TEXT,
    contributing_committee_code TEXT,
    contributing_organization TEXT,
    first_name TEXT,
    last_name TEXT,
    address_line_1 TEXT,
    address_line_2 TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    contribution_amount TEXT,
    check_number TEXT
);

CREATE TABLE ia_campaign_expenditures_landing (
    "date" TEXT,
    transaction_type TEXT,
    committee_code TEXT,
    committee_type TEXT,
    committee_name TEXT,
    receiving_committee_code TEXT,
    receiving_organization_name TEXT,
    first_name TEXT,
    last_name TEXT,
    address_line_1 TEXT,
    address_line_2 TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    expenditure_amount TEXT,
    check_number TEXT
);

CREATE TABLE ia_registered_political_candidates_landing (
    committee_name TEXT,
    committee_type TEXT,
    committee_number TEXT,
    district TEXT,
    party TEXT,
    election_year TEXT,
    election_date TEXT,
    office_sought TEXT,
    county TEXT,
    candidate_name TEXT,
    candidate_address TEXT,
    candidate_city_state_zip TEXT,
    candidate_phone TEXT,
    candidate_email TEXT,
    chair_name TEXT,
    chair_address TEXT,
    chair_city_state_zip TEXT,
    chair_phone TEXT,
    chair_email TEXT,
    treasurer_name TEXT,
    treasurer_address TEXT,
    treasurer_city_state_zip TEXT,
    treasurer_phone TEXT,
    treasurer_email TEXT,
    parent_entity TEXT,
    parent_address TEXT,
    parent_city_state_zip TEXT,
    contact_name TEXT,
    contact_address TEXT,
    contact_city_state_zip TEXT,
    contact_phone TEXT
);

CREATE TABLE ia_independent_expenditures_landing (
    organization_name TEXT,
    organization_city TEXT,
    organization_state TEXT,
    organization_zip TEXT,
    organization_email TEXT,
    contact_first_name TEXT,
    contact_last_name TEXT,
    contact_email TEXT,
    date_of_expenditure TEXT,
    amount TEXT,
    position TEXT,
    communication_description TEXT,
    communication_type TEXT,
    corporation TEXT,
    vendor TEXT,
    distribution_date TEXT,
    for_candidate TEXT,
    against_candidate TEXT,
    for_ballot_issue TEXT,
    against_ballot_issue TEXT,
    signed_date TEXT
)