-- Create Montana candidates landing table
CREATE TABLE mt_candidates_landing (
    candidate_id TEXT,
    ent_id TEXT,
    candidate_name TEXT,
    candidate_address TEXT,
    office_code TEXT,
    office_title TEXT,
    candidate_type_code TEXT,
    candidate_type_descr TEXT,
    res_county_code TEXT,
    res_county_descr TEXT,
    party_code TEXT,
    party_descr TEXT,
    own_treasurer_ind TEXT,
    election_year TEXT,
    closed_ind TEXT,
    candidate_status_code TEXT,
    candidate_status_descr TEXT,
    c3_filed_ind TEXT,
    amended_date TEXT,
    created_date TEXT,
    first_name TEXT,
    last_name TEXT,
    middle_initial TEXT,
    entity_type_descr TEXT,
    email TEXT,
    mailing_address TEXT,
    home_phone TEXT,
    work_phone TEXT
);

-- Create Montana committees landing table
CREATE TABLE mt_committees_landing (
    committee_id TEXT,
    ent_id TEXT,
    committee_name TEXT,
    committee_address TEXT,
    committee_type_code TEXT,
    committee_type_descr TEXT,
    election_year TEXT,
    over_500_ind TEXT,
    comments TEXT,
    committee_subtype_code TEXT,
    committee_subtype_descr TEXT,
    county_code TEXT,
    county_descr TEXT,
    incorporated TEXT,
    committee_status_code TEXT,
    committee_status_descr TEXT,
    c2_is_filed TEXT,
    created_date TEXT,
    amended_date TEXT,
    entity_type_code TEXT,
    entity_type_descr TEXT,
    entity_name TEXT,
    email TEXT,
    mailing_address TEXT,
    city TEXT,
    state TEXT,
    zip5 TEXT,
    zip4 TEXT,
    country_code TEXT,
    country_descr TEXT,
    phone_number TEXT,
    phone_type_code TEXT,
    phone_type_descr TEXT,
    phone_formatted TEXT
);

-- Create Montana contributions by candidate landing table
CREATE TABLE mt_contributions_by_candidate_landing (
    contribution_id TEXT,
    contribution_date TEXT,
    amount TEXT,
    candidate_id TEXT,
    candidate_name TEXT,
    office_code TEXT,
    office_title TEXT,
    election_year TEXT,
    form_type_code TEXT,
    form_type_descr TEXT,
    created_date TEXT,
    amended_date TEXT,
    -- Person DTO fields
    person_ent_id TEXT,
    person_entity_type_code TEXT,
    person_entity_type_descr TEXT,
    person_last_name TEXT,
    person_first_name TEXT,
    person_middle_initial TEXT,
    person_entity_name TEXT,
    person_salutation_code TEXT,
    person_salutation_descr TEXT,
    person_greeting_code TEXT,
    person_greeting_descr TEXT,
    person_occupation_code TEXT,
    person_occupation_descr TEXT,
    person_comments TEXT,
    person_entity_full_name TEXT,
    person_entity_address TEXT,
    person_entity_city TEXT,
    person_entity_state TEXT,
    person_first_middle_last_name TEXT,
    person_is_corporation_ind TEXT,
    person_is_fundraiser_ind TEXT,
    person_full_name TEXT,
    -- Mail Address DTO fields
    mail_address_id TEXT,
    mail_address_ent_id TEXT,
    mail_address_line1 TEXT,
    mail_address_line2 TEXT,
    mail_address_city TEXT,
    mail_address_state TEXT,
    mail_address_zip5 TEXT,
    mail_address_zip4 TEXT,
    mail_address_country_code TEXT,
    mail_address_country_descr TEXT,
    mail_address_type_code TEXT,
    mail_address_type_descr TEXT,
    mail_address_comments TEXT,
    mail_address_city_state_zip TEXT,
    -- Home Address DTO fields
    home_address_id TEXT,
    home_address_ent_id TEXT,
    home_address_line1 TEXT,
    home_address_line2 TEXT,
    home_address_city TEXT,
    home_address_state TEXT,
    home_address_zip5 TEXT,
    home_address_zip4 TEXT,
    home_address_country_code TEXT,
    home_address_country_descr TEXT,
    home_address_type_code TEXT,
    home_address_type_descr TEXT,
    home_address_comments TEXT,
    home_address_city_state_zip TEXT,
    -- Home Phone DTO fields
    home_phone_id TEXT,
    home_phone_ent_id TEXT,
    home_phone_number TEXT,
    home_phone_type_code TEXT,
    home_phone_type_descr TEXT,
    home_phone_comments TEXT,
    home_phone_formatted TEXT,
    -- Work Phone DTO fields
    work_phone_id TEXT,
    work_phone_ent_id TEXT,
    work_phone_number TEXT,
    work_phone_type_code TEXT,
    work_phone_type_descr TEXT,
    work_phone_comments TEXT,
    work_phone_formatted TEXT,
    -- Work Email DTO fields
    work_email_id TEXT,
    work_email_ent_id TEXT,
    work_email_address TEXT,
    work_email_type_code TEXT,
    work_email_type_descr TEXT,
    work_email_comments TEXT
);

-- Create Montana contributions by committee landing table
CREATE TABLE mt_contributions_by_committee_landing (
    
    contribution_id TEXT,
    contribution_date TEXT,
    amount TEXT,
    committee_id TEXT,
    committee_name TEXT,
    committee_type_code TEXT,
    committee_type_descr TEXT,
    election_year TEXT,
    form_type_code TEXT,
    form_type_descr TEXT,
    created_date TEXT,
    amended_date TEXT,

    entity_ent_id TEXT,
    entity_type_code TEXT,
    entity_type_descr TEXT,
    entity_last_name TEXT,
    entity_first_name TEXT,
    entity_middle_initial TEXT,
    entity_name TEXT,
    entity_salutation_code TEXT,
    entity_salutation_descr TEXT,
    entity_greeting_code TEXT,
    entity_greeting_descr TEXT,
    entity_occupation_code TEXT,
    entity_occupation_descr TEXT,
    entity_comments TEXT,
    entity_full_name TEXT,
    entity_address TEXT,
    entity_city TEXT,
    entity_state TEXT,
    entity_first_middle_last_name TEXT,
    entity_is_corporation_ind TEXT,
    entity_is_fundraiser_ind TEXT,
    
    mail_address_id TEXT,
    mail_address_ent_id TEXT,
    mail_address_line1 TEXT,
    mail_address_line2 TEXT,
    mail_address_city TEXT,
    mail_address_state TEXT,
    mail_address_zip5 TEXT,
    mail_address_zip4 TEXT,
    mail_address_country_code TEXT,
    mail_address_country_descr TEXT,
    mail_address_type_code TEXT,
    mail_address_type_descr TEXT,
    mail_address_comments TEXT,
    mail_address_city_state_zip TEXT,
   
    home_address_id TEXT,
    home_address_ent_id TEXT,
    home_address_line1 TEXT,
    home_address_line2 TEXT,
    home_address_city TEXT,
    home_address_state TEXT,
    home_address_zip5 TEXT,
    home_address_zip4 TEXT,
    home_address_country_code TEXT,
    home_address_country_descr TEXT,
    home_address_type_code TEXT,
    home_address_type_descr TEXT,
    home_address_comments TEXT,
    home_address_city_state_zip TEXT,
   
    home_phone_id TEXT,
    home_phone_ent_id TEXT,
    home_phone_number TEXT,
    home_phone_type_code TEXT,
    home_phone_type_descr TEXT,
    home_phone_comments TEXT,
    home_phone_formatted TEXT,
    
    work_phone_id TEXT,
    work_phone_ent_id TEXT,
    work_phone_number TEXT,
    work_phone_type_code TEXT,
    work_phone_type_descr TEXT,
    work_phone_comments TEXT,
    work_phone_formatted TEXT,

    work_email_id TEXT,
    work_email_ent_id TEXT,
    work_email_address TEXT,
    work_email_type_code TEXT,
    work_email_type_descr TEXT,
    work_email_comments TEXT
);

-- Create mt_expenditure_by_candidate_landing table
CREATE TABLE mt_expenditure_by_candidate_landing (
    expenditure_id TEXT,
    expenditure_date TEXT,
    amount TEXT,
    candidate_id TEXT,
    candidate_name TEXT,
    office_code TEXT,
    office_title TEXT,
    election_year TEXT,
    form_type_code TEXT,
    form_type_descr TEXT,
    created_date TEXT,
    amended_date TEXT,
    -- Entity DTO fields
    entity_ent_id TEXT,
    entity_type_code TEXT,
    entity_type_descr TEXT,
    entity_last_name TEXT,
    entity_first_name TEXT,
    entity_middle_initial TEXT,
    entity_name TEXT,
    entity_salutation_code TEXT,
    entity_salutation_descr TEXT,
    entity_greeting_code TEXT,
    entity_greeting_descr TEXT,
    entity_occupation_code TEXT,
    entity_occupation_descr TEXT,
    entity_comments TEXT,
    entity_full_name TEXT,
    entity_address TEXT,
    entity_city TEXT,
    entity_state TEXT,
    entity_first_middle_last_name TEXT,
    entity_is_corporation_ind TEXT,
    entity_is_fundraiser_ind TEXT,
    -- Mail Address DTO fields
    mail_address_id TEXT,
    mail_address_ent_id TEXT,
    mail_address_line1 TEXT,
    mail_address_line2 TEXT,
    mail_address_city TEXT,
    mail_address_state TEXT,
    mail_address_zip5 TEXT,
    mail_address_zip4 TEXT,
    mail_address_country_code TEXT,
    mail_address_country_descr TEXT,
    mail_address_type_code TEXT,
    mail_address_type_descr TEXT,
    mail_address_comments TEXT,
    mail_address_city_state_zip TEXT,
    -- Home Address DTO fields
    home_address_id TEXT,
    home_address_ent_id TEXT,
    home_address_line1 TEXT,
    home_address_line2 TEXT,
    home_address_city TEXT,
    home_address_state TEXT,
    home_address_zip5 TEXT,
    home_address_zip4 TEXT,
    home_address_country_code TEXT,
    home_address_country_descr TEXT,
    home_address_type_code TEXT,
    home_address_type_descr TEXT,
    home_address_comments TEXT,
    home_address_city_state_zip TEXT,
    -- Home Phone DTO fields
    home_phone_id TEXT,
    home_phone_ent_id TEXT,
    home_phone_number TEXT,
    home_phone_type_code TEXT,
    home_phone_type_descr TEXT,
    home_phone_comments TEXT,
    home_phone_formatted TEXT,
    -- Work Phone DTO fields
    work_phone_id TEXT,
    work_phone_ent_id TEXT,
    work_phone_number TEXT,
    work_phone_type_code TEXT,
    work_phone_type_descr TEXT,
    work_phone_comments TEXT,
    work_phone_formatted TEXT,
    -- Work Email DTO fields
    work_email_id TEXT,
    work_email_ent_id TEXT,
    work_email_address TEXT,
    work_email_type_code TEXT,
    work_email_type_descr TEXT,
    work_email_comments TEXT
);

-- Create mt_expenditure_by_committee_landing table
CREATE TABLE mt_expenditure_by_committee_landing (
    -- Basic expenditure fields
    expenditure_id TEXT,
    expenditure_date TEXT,
    amount TEXT,
    committee_id TEXT,
    committee_name TEXT,
    committee_type_code TEXT,
    committee_type_descr TEXT,
    election_year TEXT,
    form_type_code TEXT,
    form_type_descr TEXT,
    created_date TEXT,
    amended_date TEXT,
    -- Entity DTO fields
    entity_ent_id TEXT,
    entity_type_code TEXT,
    entity_type_descr TEXT,
    entity_last_name TEXT,
    entity_first_name TEXT,
    entity_middle_initial TEXT,
    entity_name TEXT,
    entity_salutation_code TEXT,
    entity_salutation_descr TEXT,
    entity_greeting_code TEXT,
    entity_greeting_descr TEXT,
    entity_occupation_code TEXT,
    entity_occupation_descr TEXT,
    entity_comments TEXT,
    entity_full_name TEXT,
    entity_address TEXT,
    entity_city TEXT,
    entity_state TEXT,
    entity_first_middle_last_name TEXT,
    entity_is_corporation_ind TEXT,
    entity_is_fundraiser_ind TEXT,
    -- Mail Address DTO fields
    mail_address_id TEXT,
    mail_address_ent_id TEXT,
    mail_address_line1 TEXT,
    mail_address_line2 TEXT,
    mail_address_city TEXT,
    mail_address_state TEXT,
    mail_address_zip5 TEXT,
    mail_address_zip4 TEXT,
    mail_address_country_code TEXT,
    mail_address_country_descr TEXT,
    mail_address_type_code TEXT,
    mail_address_type_descr TEXT,
    mail_address_comments TEXT,
    mail_address_city_state_zip TEXT,
    -- Home Address DTO fields
    home_address_id TEXT,
    home_address_ent_id TEXT,
    home_address_line1 TEXT,
    home_address_line2 TEXT,
    home_address_city TEXT,
    home_address_state TEXT,
    home_address_zip5 TEXT,
    home_address_zip4 TEXT,
    home_address_country_code TEXT,
    home_address_country_descr TEXT,
    home_address_type_code TEXT,
    home_address_type_descr TEXT,
    home_address_comments TEXT,
    home_address_city_state_zip TEXT,
    -- Home Phone DTO fields
    home_phone_id TEXT,
    home_phone_ent_id TEXT,
    home_phone_number TEXT,
    home_phone_type_code TEXT,
    home_phone_type_descr TEXT,
    home_phone_comments TEXT,
    home_phone_formatted TEXT,
    -- Work Phone DTO fields
    work_phone_id TEXT,
    work_phone_ent_id TEXT,
    work_phone_number TEXT,
    work_phone_type_code TEXT,
    work_phone_type_descr TEXT,
    work_phone_comments TEXT,
    work_phone_formatted TEXT,
    -- Work Email DTO fields
    work_email_id TEXT,
    work_email_ent_id TEXT,
    work_email_address TEXT,
    work_email_type_code TEXT,
    work_email_type_descr TEXT,
    work_email_comments TEXT
);




