CREATE TABLE wa_campaign_finance_reporting_history_landing (
    report_number text,
    amends_report text,
    amended_by_report text,
    origin text,
    committee_id text,
    filer_id text,
    election_year text,
    type text,
    filer_name text,
    office text,
    legislative_district text,
    position text,
    party text,
    ballot_number text,
    for_or_against text,
    jurisdiction text,
    jurisdiction_county text,
    jurisdiction_type text,
    receipt_date text,
    filing_method text,
    report_from text,
    report_through text,
    url text,
    user_data text,
    metadata text,
    version text,
    attachments text
);

CREATE TABLE wa_campaign_finance_summary_landing (
    id text,
    filer_id text,
    filer_type text,
    registered text,
    declared text,
    withdrew text,
    discontinued text,
    filing_type text,
    receipt_date text,
    election_year text,
    candidate_committee_status text,
    filer_name text,
    committee_acronym text,
    committee_address text,
    committee_city text,
    committee_county text,
    committee_state text,
    committee_zip text,
    committee_email text,
    candidate_email text,
    candidate_committee_phone text,
    office text,
    office_code text,
    jurisdiction text,
    jurisdiction_code text,
    jurisdiction_county text,
    jurisdiction_type text,
    jurisdiction_voters text,
    jurisdiction_reporting_code text,
    jurisdiction_reporting_requirement text,
    committee_category text,
    political_committee_type text,
    bonafide_committee text,
    bonafide_type text,
    position text,
    party_code text,
    party text,
    election_date text,
    reporting_option text,
    active_candidate text,
    on_primary_election_ballot text,
    on_general_election_ballot text,
    primary_election_status text,
    general_election_status text,
    election_status text,
    exempt_nonexempt text,
    ballot_committee text,
    ballot_proposal_count text,
    ballot_number text,
    ballot_title text,
    for_or_against text,
    ballot_proposal_detail text,
    other_pac text,
    treasurer_address text,
    treasurer_city text,
    treasurer_state text,
    treasurer_zip text,
    treasurer_phone text,
    contributions_amount text,
    carryforward_amount text,
    expenditures_amount text,
    loans_amount text,
    pledges_amount text,
    debts_amount text,
    independent_expenditures_for_amount text,
    independent_expenditures_against_amount text,
    url text,
    committee_id text,
    person_id text,
    candidacy_id text,
    fund_id text,
    legislative_district text,
    treasurer_name text,
    pac_type text,
    continuing text,
    updated_at text
);

CREATE TABLE wa_candidate_surplus_funds_latest_report_landing (
    id text,
    report_number text,
    origin text,
    filer_id text,
    person_id text,
    filer_name text,
    from_date text,
    thru_date text,
    year text,
    raised text,
    spent text,
    balance text,
    url text
);

CREATE TABLE wa_candidate_surplus_funds_reports_landing (
    id text,
    report_number text,
    amends_report text,
    amended_by_report text,
    origin text,
    filer_id text,
    person_id text,
    filer_name text,
    from_date text,
    thru_date text,
    year text,
    raised text,
    spent text,
    balance text,
    url text,
    committee_id text,
    metadata text,
    attachments text,
    version text
);

CREATE TABLE wa_contributions_to_candidates_and_political_committees_landing (
    id text,
    report_number text,
    origin text,
    committee_id text,
    filer_id text,
    type text,
    filer_name text,
    office text,
    legislative_district text,
    position text,
    party text,
    ballot_number text,
    for_or_against text,
    jurisdiction text,
    jurisdiction_county text,
    jurisdiction_type text,
    election_year text,
    amount text,
    cash_or_in_kind text,
    receipt_date text,
    description text,
    memo text,
    primary_general text,
    code text,
    contributor_category text,
    contributor_name text,
    contributor_address text,
    contributor_city text,
    contributor_state text,
    contributor_zip text,
    contributor_occupation text,
    contributor_employer_name text,
    contributor_employer_city text,
    contributor_employer_state text,
    url text,
    contributor_location text
);

CREATE TABLE wa_lobbyist_employers_summary_landing (
    id text,
    year text,
    employer_name text,
    employer_email text,
    employer_phone text,
    employer_address text,
    employer_city text,
    employer_state text,
    employer_zip text,
    employer_country text,
    compensation text,
    expenditures text,
    agg_contrib text,
    ballot_prop text,
    entertain text,
    vendor text,
    expert_retain text,
    inform_material text,
    lobbying_comm text,
    ie_in_support text,
    itemized_exp text,
    other_l3_exp text,
    political text,
    corr_compensation text,
    corr_expend text,
    total_exp text,
    l3_nid text,
    employer_nid text,
    url text
);

CREATE TABLE wa_lobbyist_employment_registrations_landing (
    id text,
    report_number text,
    lobbyist_id text,
    lobbyist_name text,
    lobbyist_url text,
    employer_id text,
    employer_name text,
    employer_url text,
    employment_year text,
    contractor_id text,
    contractor_name text,
    contractor_url text,
    employment_url text,
    employment_period text
);

CREATE TABLE wa_lobbyist_summary_landing (
    id text,
    year text,
    filer_id text,
    lobbyist_name text,
    lobbyist_email text,
    lobbyist_phone text,
    firm_address text,
    firm_city text,
    firm_state text,
    firm_zip text,
    firm_country text,
    temp_phone text,
    temp_address text,
    temp_city text,
    temp_state text,
    temp_zip text,
    temp_country text,
    compensation text,
    sub_lobbyist_compensation text,
    net_compensation text,
    personal_expenses text,
    entertainment text,
    contributions text,
    pac_contributions text,
    advertising text,
    political_ads text,
    independent_expenditures_candidate text,
    independent_expenditures_ballot text,
    other text,
    direct_lobbying_expenses text,
    indirect_lobbying_expenses text,
    total_expenses text,
    net_total text,
    use_categories text,
    periods text
);

CREATE TABLE wa_pledges_reporting_history_landing (
    id text,
    report_number text,
    origin text,
    committee_id text,
    filer_id text,
    type text,
    filer_name text,
    office text,
    legislative_district text,
    position text,
    party text,
    ballot_number text,
    for_or_against text,
    jurisdiction text,
    jurisdiction_county text,
    jurisdiction_type text,
    election_year text,
    amount text,
    receipt_date text,
    primary_general text,
    code text,
    contributor_name text,
    contributor_address text,
    contributor_city text,
    contributor_state text,
    contributor_zip text,
    contributor_occupation text,
    contributor_employer_name text,
    contributor_employer_city text,
    contributor_employer_state text,
    url text
);

CREATE TABLE wa_pre_2016_lobbyist_compensation_and_expenses_by_source_landing (
    id text,
    report_number text,
    origin text,
    filer_id text,
    filer_name text,
    type text,
    funding_source_id text,
    funding_source_name text,
    filing_period text,
    receipt_date text,
    employer_id text,
    employer_name text,
    compensation text,
    personal_expenses text,
    entertainment text,
    contributions text,
    advertising text,
    political_ads text,
    other text,
    new_filer_id text,
    new_employer_id text
);

CREATE TABLE wa_pre_2016_lobbyist_employment_registration_landing (
    id text,
    lobbyist_id text,
    lobbyist_name text,
    employer_id text,
    employer_name text,
    employment_year text,
    contractor text,
    contractor_name text,
    new_filer_id text,
    new_employer_id text
);

CREATE TABLE wa_debt_reported_by_candidates_and_political_committees_landing (
    id text,
    report_number text,
    origin text,
    committee_id text,
    filer_id text,
    filer_type text,
    filer_name text,
    office text,
    legislative_district text,
    position text,
    party text,
    jurisdiction text,
    jurisdiction_county text,
    jurisdiction_type text,
    election_year text,
    amount text,
    record_type text,
    from_date text,
    thru_date text,
    debt_date text,
    code text,
    description text,
    vendor_name text,
    vendor_address text,
    vendor_city text,
    vendor_state text,
    vendor_zip text,
    url text
);

CREATE TABLE wa_public_agency_lobbying_totals_landing (
    id text,
    filer_id text,
    name text,
    address text,
    city text,
    state text,
    zip_code text,
    contact text,
    email_address text,
    phone text,
    year text,
    q1_report_num text,
    q1 text,
    q2_report_num text,
    q2 text,
    q3_report_num text,
    q3 text,
    q4_report_num text,
    q4 text,
    year_total text,
    q1_url text,
    q2_url text,
    q3_url text,
    q4_url text
);

CREATE TABLE wa_expenditures_by_candidates_and_political_committees_landing (
    id text,
    report_number text,
    origin text,
    committee_id text,
    filer_id text,
    type text,
    filer_name text,
    office text,
    legislative_district text,
    position text,
    party text,
    ballot_number text,
    for_or_against text,
    jurisdiction text,
    jurisdiction_county text,
    jurisdiction_type text,
    election_year text,
    amount text,
    itemized_or_non_itemized text,
    expenditure_date text,
    description text,
    code text,
    recipient_name text,
    recipient_address text,
    recipient_city text,
    recipient_state text,
    recipient_zip text,
    url text,
    recipient_location text,
    payee text,
    creditor text
);

CREATE TABLE wa_surplus_funds_expenditures_landing (
    id text,
    report_number text,
    origin text,
    filer_id text,
    person_id text,
    type text,
    filer_name text,
    election_year text,
    amount text,
    itemized_or_non_itemized text,
    expenditure_date text,
    description text,
    code text,
    recipient_name text,
    recipient_address text,
    recipient_city text,
    recipient_state text,
    recipient_zip text,
    url text,
    recipient_location text
);

CREATE TABLE wa_financial_affairs_disclosures_landing (
    id text,
    submission_id text,
    report_number text,
    filer_id text,
    person_id text,
    name text,
    receipt_date text,
    period_start text,
    period_end text,
    json text,
    url text,
    certification_name text,
    certification_email text,
    certification_phone text,
    candidacies text,
    offices text,
    certification text,
    history text
);

CREATE TABLE wa_voter_address_precinct_crosswalk_landing (
    streetaddress text,
    street_city text,
    street text,
    regstnum text,
    regcity text,
    regstate text,
    regzipcode text,
    precinctcode text,
    levycode text,
    countycode text
);

CREATE TABLE wa_imaged_documents_and_reports_landing (
    id text,
    report_number text,
    origin text,
    document_description text,
    filer_id text,
    type text,
    filer_name text,
    office text,
    legislative_district text,
    party text,
    election_year text,
    receipt_date text,
    processed_date text,
    filing_method text,
    report_from text,
    report_to text,
    url text
);

CREATE TABLE wa_voter_precinct_to_jurisdiction_crosswalk_landing (
    districtid text,
    precinctid text,
    precinctcode text,
    levycode text,
    countycode text,
    jurisdiction_code text,
    office_code text,
    jurisdiction_county text
);

CREATE TABLE wa_independent_campaign_expenditures_and_electioneering_communications_landing (
    id text,
    report_number text,
    origin text,
    sponsor_entity_id text,
    sponsor_id text,
    sponsor_name text,
    sponsor_description text,
    report_type text,
    report_date text,
    election_year text,
    sponsor_address text,
    sponsor_city text,
    sponsor_state text,
    sponsor_zip text,
    sponsor_email text,
    sponsor_phone text,
    total_unitemized text,
    total_cycle text,
    total_this_report text,
    expenditure_amount text,
    expenditure_description text,
    date_expense_obligated text,
    date_advertising_presented text,
    vendor_name text,
    vendor_address text,
    vendor_city text,
    vendor_state text,
    vendor_zipcode text,
    candidate_entity_id text,
    candidate_candidacy_id text,
    candidate_committee_id text,
    candidate_filer_id text,
    candidate_name text,
    candidate_last_name text,
    candidate_first_name text,
    candidate_office text,
    candidate_jurisdiction text,
    candidate_party text,
    candidate_office_type text,
    ballot_name text,
    ballot_number text,
    ballot_type text,
    portion_of_amount text,
    for_or_against text,
    funders_name text,
    funders_first_name text,
    funders_middle_initial text,
    date_received text,
    amount text,
    funders_address text,
    funders_city text,
    funders_state text,
    funders_zipcode text,
    funders_occupation text,
    funders_employer text,
    funders_employer_city text,
    funders_employer_state text,
    url text,
    sponsor_location text,
    vendor_location text,
    funders_location text,
    filer_id text
);

CREATE TABLE wa_loans_to_candidates_and_political_committees_landing (
    id text,
    report_number text,
    origin text,
    committee_id text,
    filer_id text,
    type text,
    filer_name text,
    office text,
    legislative_district text,
    position text,
    party text,
    jurisdiction text,
    jurisdiction_county text,
    jurisdiction_type text,
    election_year text,
    cash_or_in_kind text,
    receipt_date text,
    repayment_schedule text,
    loan_due_date text,
    lender_or_endorser text,
    transaction_type text,
    amount text,
    endorser_liable_amount text,
    primary_general text,
    lenders_name text,
    lenders_address text,
    lenders_city text,
    lenders_state text,
    lenders_zip text,
    lenders_occupation text,
    lenders_employer text,
    employers_city text,
    employers_state text,
    url text,
    carry_forward_loan text,
    description text
);

CREATE TABLE wa_lobbyist_agent_employers_landing (
    id text,
    filer_id text,
    lobbyist_firm_name text,
    lobbyist_phone text,
    lobbyist_email text,
    lobbyist_address text,
    employment_registration_id text,
    employment_registration_title text,
    employer_id text,
    employer_title text,
    agent_name text,
    agent_bio text,
    agent_pic_url text,
    employment_year text,
    lobbyist_firm_url text,
    employment_registration_url text,
    employer_url text,
    training_certified text
);

CREATE TABLE wa_lobbyist_agents_landing (
    id text,
    filer_id text,
    lobbyist_firm_name text,
    lobbyist_phone text,
    lobbyist_email text,
    lobbyist_address text,
    employers text,
    agent_name text,
    agent_bio text,
    agent_pic_url text,
    employment_year text,
    lobbyist_firm_url text,
    training_certified text
);

CREATE TABLE wa_lobbyist_compensation_and_expenses_by_source_landing (
    id text,
    report_number text,
    origin text,
    filer_id text,
    filer_name text,
    type text,
    funding_source_id text,
    funding_source text,
    filing_period text,
    first_filed_at text,
    receipt_date text,
    employer_id text,
    employer_name text,
    compensation text,
    sub_lobbyist_compensation text,
    net_compensation text,
    personal_expenses text,
    entertainment text,
    contributions text,
    advertising text,
    political_ads text,
    independent_expenditures_candidate text,
    independent_expenditures_ballot text,
    other text,
    direct_expenses text,
    indirect_expenses text,
    contributions_total text,
    total_expenses text,
    net_total text,
    employment_registration_id text,
    employment_type text,
    contractor_id text,
    contractor_name text,
    url text
);

CREATE TABLE wa_pdc_enforcement_case_attachments_landing (
    id text,
    "case" text,
    case_opened text,
    subject text,
    document_type text,
    description text,
    file_name text,
    url text,
    case_url text
);

CREATE TABLE wa_pdc_enforcement_cases_landing (
    id text,
    "case" text,
    opened text,
    earliest_complaint text,
    closed text,
    complainant text,
    respondent text,
    subject text,
    areas_of_law text,
    status text,
    group_enforcement text,
    description text,
    url text,
    total_penalties text,
    total_suspended text,
    total_reinstated text,
    total_paid text,
    balance_due text,
    sent_to_collections text,
    attachments text,
    penalties text,
    updated_at text
);

CREATE TABLE wa_out_of_state_committee_expenditures_landing (
    id text,
    report_id text,
    filer_name text,
    committee_id text,
    committee_address text,
    committee_city text,
    committee_state text,
    committee_zip text,
    entity_id text,
    election_year text,
    expense_date text,
    amount text,
    recipient_type text,
    recipient_committee_email text,
    recipient_committee_id text,
    recipient_candidacy_id text,
    recipient_name text,
    recipient_office text,
    recipient_jurisdiction text,
    recipient_party text,
    description text,
    purpose text,
    ballot_number text,
    for_or_against text,
    inkind text,
    vendor_name text,
    vendor_city text,
    vendor_state text,
    vendor_postcode text,
    vendor_address text,
    url text,
    committee_email text,
    inkind_description text
);

CREATE TABLE wa_contributions_to_out_of_state_political_committees_landing (
    id text,
    report_id text,
    filer_name text,
    election_year text,
    committee_id text,
    committee_address text,
    committee_city text,
    committee_state text,
    committee_zip text,
    committee_email text,
    entity_id text,
    contribution_date text,
    aggregate_total text,
    amount text,
    resident text,
    name text,
    address text,
    city text,
    state text,
    postcode text,
    employer text,
    employer_address text,
    employer_city text,
    employer_state text,
    url text
);

CREATE TABLE wa_lobbyist_reporting_history_landing (
    origin text,
    id text,
    amends_report text,
    amended_by_report text,
    filer_name text,
    filer_type text,
    entity_id text,
    firm_id text,
    client_id text,
    year text,
    receipt_date text,
    filing_method text,
    report_from text,
    report_through text,
    url text,
    report_data text,
    version text
);

CREATE TABLE wa_public_disclosure_reporting_periods_landing (
    id text,
    report_type text,
    reporting_period_type text,
    start_date text,
    end_date text,
    due_date text,
    election_date text
);

