version: 2

models:
  - name: illinois_individual_contributions_transform
    description: >
      Transformed individual contribution data from Illinois campaign finance reports.
    columns:
      - name: source
        description: Source system identifier, 'IL' for Illinois
        tests:
          - accepted_values:
              values: ['IL']

      - name: source_id
        description: Unique ID for the contribution, prefixed with 'IL_'
        tests:
          - not_null
          - unique
          - assert_has_prefix:
              prefix: IL_

      - name: committee_id
        description: Committee ID, prefixed with 'IL_'
        tests:
          - not_null
          - assert_has_prefix:
              prefix: IL_

      - name: candidate_id
        description: Candidate ID associated with the contribution, prefixed with 'IL_'
        tests:
          - assert_has_prefix:
              prefix: IL_

      - name: name
        description: Contributor full name
        tests:
          - not_null

      - name: candidate_name
        description: Candidate full name (FirstName + LastName)

      - name: city
        description: Contributor city

      - name: state
        description: Contributor state

      - name: zip_code
        description: Contributor ZIP code

      - name: employer
        description: Contributor's employer

      - name: occupation
        description: Contributor's occupation

      - name: amount
        description: Contribution amount (numeric)
        tests:
          - not_null

      - name: contribution_datetime
        description: Timestamp when contribution was submitted
        tests:
          - not_null

      - name: insert_datetime
        description: When this record was inserted into the database
        tests:
          - not_null

  - name: illinois_committee_master_transform
    description: >
      Transformed Illinois committee data mapped into the unified committee master schema.
    columns:
      - name: source
        description: Static source identifier, 'IL' for Illinois
        tests:
          - accepted_values:
              values: ['IL']

      - name: committee_id
        description: Prefixed committee ID
        tests:
          - not_null
          - unique
          - assert_has_prefix:
              prefix: IL_

      - name: committee_designation
        description: Committee designation (P = Candidate, U = Other)

      - name: name
        description: Committee name
        tests:
          - not_null

      - name: candidate_id
        description: Candidate ID linked to this committee, prefixed with 'IL_'
        tests:
          - assert_has_prefix:
              prefix: IL_

      - name: candidate_name
        description: Candidate full name (FirstName + LastName)

      - name: address1
        description: Primary address line

      - name: address2
        description: Secondary address line

      - name: city
        description: Committee city

      - name: state
        description: Committee state

      - name: zip_code
        description: Committee ZIP code

      - name: affiliation
        description: Political affiliation/party

      - name: district
        description: District of the election the committee is associated with

      - name: insert_datetime
        description: Timestamp of record insertion in UTC
        tests:
          - not_null

  - name: illinois_candidate_master_transform
    description: >
      Transformed Illinois candidate data mapped into the unified candidate master schema.
    columns:
      - name: source
        description: Static source identifier, 'IL' for illinois
        tests:
          - accepted_values:
              values: ['IL']

      - name: candidate_id
        description: Prefixed org_id derived candidate identifier
        tests:
          - not_null
          - unique
          - assert_has_prefix:
              prefix: IL_

      - name: name
        description: Candidate name
        tests:
          - not_null

      - name: affiliation
        description: Party affiliation when known

      - name: district
        description: District when known

      - name: insert_datetime
        description: Timestamp of record insertion in UTC
        tests:
          - not_null
