CREATE TABLE ky_candidates_landing (
    last_name TEXT,
    first_name TEXT,
    office_sought TEXT,
    is_active_label TEXT,
    location TEXT,
    election_date TEXT,
    election_type TEXT,
    exemption_status TEXT,
    total_receipts TEXT,
    total_disburse TEXT
);

CREATE TABLE ky_contributions_landing (
    to_organization TEXT,
    from_organization_name TEXT,
    contributor_last_name TEXT,
    contributor_first_name TEXT,
    recipient_last_name TEXT,
    recipient_first_name TEXT,
    office_sought TEXT,
    location TEXT,
    election_date TEXT,
    election_type TEXT,
    exemption_status TEXT,
    other_text TEXT,
    address1 TEXT,
    address2 TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    amount TEXT,
    contribution_type TEXT,
    contribution_mode TEXT,
    occupation TEXT,
    other_occupation TEXT,
    employer TEXT,
    spouse_prefix TEXT,
    spouse_last_name TEXT,
    spouse_first_name TEXT,
    spouse_middle_initial TEXT,
    spouse_suffix TEXT,
    spouse_occupation TEXT,
    spouse_employer TEXT,
    number_of_contributors TEXT,
    inkind_description TEXT,
    receipt_date TEXT,
    statement_type TEXT
);

CREATE TABLE ky_expenditures_landing (
    recipient_last_name TEXT,
    recipient_first_name TEXT,
    organization_name TEXT,
    purpose TEXT,
    occupation TEXT,
    disbursement_code TEXT,
    disbursement_amount TEXT,
    disbursement_date TEXT,
    from_candidate_first_name TEXT,
    from_candidate_last_name TEXT,
    from_organization_name TEXT,
    statement_type TEXT,
    office_sought TEXT,
    election_date TEXT,
    election_type TEXT,
    is_independent_expenditure TEXT
);
