-- Colorado Contributions Landing Table
CREATE TABLE co_contributions_landing (
    "CO_ID" text,
    "ContributionAmount" text,
    "ContributionDate" text,
    "LastName" text,
    "FirstName" text,
    "MI" text,
    "Suffix" text,
    "Address1" text,
    "Address2" text,
    "City" text,
    "State" text,
    "Zip" text,
    "Explanation" text,
    "RecordID" text,
    "FiledDate" text,
    "ContributionType" text,
    "ReceiptType" text,
    "ContributorType" text,
    "Electioneering" text,
    "CommitteeType" text,
    "CommitteeName" text,
    "CandidateName" text,
    "Employer" text,
    "Occupation" text,
    "Amended" text,
    "Amendment" text,
    "AmendedRecordID" text,
    "Jurisdiction" text,
    "OccupationComments" text
);

-- Colorado Loans Landing Table
CREATE TABLE co_loans_landing (
    "CO_ID" text,
    "PaymentAmount" text,
    "PaymentDate" text,
    "Name" text,
    "Address1" text,
    "Address2" text,
    "City" text,
    "State" text,
    "Zip" text,
    "Description" text,
    "RecordID" text,
    "FiledDate" text,
    "Type" text,
    "LoanSourceType" text,
    "LoanAmount" text,
    "LoanDate" text,
    "CommitteeType" text,
    "CommitteeName" text,
    "CandidateName" text,
    "InterestRate" text,
    "InterestPayment" text,
    "Amended" text,
    "Amendment" text,
    "AmendedRecordID" text,
    "Jurisdiction" text,
    "LoanBalance" text
);

-- Colorado Expenditures Landing Table
CREATE TABLE co_expenditures_landing (
    "CO_ID" text,
    "ExpenditureAmount" text,
    "ExpenditureDate" text,
    "LastName" text,
    "FirstName" text,
    "MI" text,
    "Suffix" text,
    "Address1" text,
    "Address2" text,
    "City" text,
    "State" text,
    "Zip" text,
    "Explanation" text,
    "RecordID" text,
    "FiledDate" text,
    "ExpenditureType" text,
    "PaymentType" text,
    "DisbursementType" text,
    "Electioneering" text,
    "CommitteeType" text,
    "CommitteeName" text,
    "CandidateName" text,
    "Employer" text,
    "Occupation" text,
    "Amended" text,
    "Amendment" text,
    "AmendedRecordID" text,
    "Jurisdiction" text
);
