CREATE TABLE ne_contributions_loan_landing (
    receipt_id TEXT,
    org_id TEXT,
    filer_type TEXT,
    filer_name TEXT,
    candidate_name TEXT,
    receipt_transaction_contribution_type TEXT,
    other_funds_type TEXT,
    receipt_date TEXT,
    receipt_amount TEXT,
    "description" TEXT,
    contributor_or_transaction_source_type TEXT,
    contributor_or_source_last_name TEXT,
    first_name TEXT,
    middle_name TEXT,
    suffix TEXT,
    address_1 TEXT,
    address_2 TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    filed_date TEXT,
    amended TEXT,
    employer TEXT,
    occupation TEXT
);

CREATE TABLE ne_expenditures_landing (
    expenditure_id TEXT,
    org_id TEXT,
    filer_type TEXT,
    filer_name TEXT,
    candidate_name TEXT,
    expenditure_transaction_type TEXT,
    expenditure_sub_type TEXT,
    expenditure_date TEXT,
    expenditure_amount TEXT,
    "description" TEXT,
    contributor_type TEXT,
    contributor_name TEXT,
    first_name TEXT,
    middle_name TEXT,
    suffix TEXT,
    address_1 TEXT,
    address_2 TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    filed_date TEXT,
    support_or_oppose TEXT,
    ballot_issue_or_candidate_name TEXT,
    jurisdiction_description TEXT,
    amended TEXT,
    employer TEXT,
    occupation TEXT,
    principal_place_of_business TEXT
);
