CREATE TABLE wi_filed_reports_landing (
    filing_period_name TEXT,
    report_type_code TEXT,
    report_name TEXT,
    registrant_type TEXT,
    date_filed TEXT,
    amended_date TEXT,
    committee_id TEXT,
    registrant_name TEXT,
    election_year TEXT,
    branch TEXT,
    filing_year TEXT,
    extension TEXT,
    comment_flag TEXT,
    attachment TEXT,
    view_report_type TEXT,
    created_date TEXT,
    empty_column TEXT
);

CREATE TABLE wi_receipt_transactions_landing (
    transaction_date TEXT,
    filing_period_name TEXT,
    contributor_name TEXT,
    contribution_amount TEXT,
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    state_code TEXT,
    zip TEXT,
    occupation TEXT,
    employer_name TEXT,
    employer_address TEXT,
    contributor_type TEXT,
    receiving_committee_name TEXT,
    ethcfid TEXT,
    conduit TEXT,
    branch TEXT,
    comment TEXT,
    report_72hr TEXT,
    segregated_fund_flag TEXT,
    empty_column TEXT
);

CREATE TABLE wi_expense_transactions_landing (
    registrant_name TEXT,
    ethcfid TEXT,
    branch TEXT,
    payee_name TEXT,
    transaction_date TEXT,
    communication_date TEXT,
    expense_purpose TEXT,
    expense_category TEXT,
    filing_period_name TEXT,
    filing_fee_name TEXT,
    recount_name TEXT,
    recall_name TEXT,
    referendum_name TEXT,
    ind_exp_candidate_name TEXT,
    support_oppose TEXT,
    amount TEXT,
    comment TEXT,
    reports_72_hr TEXT,
    payee_address_line1 TEXT,
    payee_address_line2 TEXT,
    payee_city TEXT,
    payee_state TEXT,
    zip TEXT,
    segregated_fund_flag TEXT,
    empty_column TEXT
);

CREATE TABLE wi_registered_committees_landing (
    registrant_type TEXT,
    committee_id TEXT,
    committee_name TEXT,
    committee_address TEXT,
    registrant_status TEXT,
    election_date TEXT,
    branch TEXT,
    registered_date TEXT,
    amended_date TEXT,
    out_state TEXT,
    referendum TEXT,
    independent TEXT,
    exempt TEXT,
    termination_requested_date TEXT,
    empty_column TEXT
);