version: 2

models:
  - name: kansas_individual_contributions_transform
    description: >
      Transformed individual contribution data from Kansas campaign finance reports
    columns:
      - name: source
        description: Source system identifier, 'KS' for Kansas
        tests:
          - accepted_values:
              values: ['KS']

      - name: source_id
        description: Unique ID for the contribution, prefixed with 'KS_'
        tests:
          - not_null
          - unique
          - assert_has_prefix:
              prefix: KS_


      - name: committee_id
        description: Committee ID, prefixed with 'KS_'
        tests:
          - not_null

      - name: name
        description: Contributor name
        tests:
          - not_null

      - name: city
        description: Contributor city

      - name: state
        description: Contributor state

      - name: zip_code
        description: Contributor ZIP code

      - name: employer
        description: Contributor's employer

      - name: occupation
        description: Contributor's occupation

      - name: amount
        description: Contribution amount (numeric)
        tests:
          - not_null

      - name: contribution_datetime
        description: Timestamp when contribution was submitted
        tests:
          - not_null

      - name: insert_datetime
        description: When this record was inserted into the database
        tests:
          - not_null

  - name: kansas_committee_master_transform
    description: >
      Transformed Kansas committee data mapped into the unified committee master schema.
      Each row represents a committee with normalized structure and a unique generated ID.
    columns:
      - name: source
        description: Static source identifier, 'KS' for Kansas
        tests:
          - accepted_values:
              values: ['KS']

      - name: committee_id
        description: Generated unique ID for the committee, prefixed with 'KS_'
        tests:
          - not_null
          - unique

      - name: committee_designation
        description: Committee designation (currently null)

      - name: name
        description: Committee name
        tests:
          - not_null

      - name: address1
        description: Primary address line

      - name: address2
        description: Secondary address line

      - name: city
        description: Committee city

      - name: state
        description: Committee state

      - name: zip_code
        description: Committee ZIP code

      - name: affiliation
        description: Political affiliation/party

      - name: district
        description: District of the election the committee is associated with

      - name: insert_datetime
        description: Timestamp of record insertion in UTC
        tests:
          - not_null
