DROP TABLE wv_candidates_landing;

CREATE TABLE wv_candidates_landing (
    "CandidateName" TEXT,
    "OfficeName" TEXT,
    "ElectionYear" TEXT,
    "Party" TEXT,
    "District" TEXT,
    "Jurisdiction" TEXT,
    "FinanceType" TEXT,
    "Status" TEXT,
    "Incumbent" TEXT,
    "IDNumber" TEXT,
    "TreasurerName" TEXT,
    "CandidateAddress" TEXT,
    "RegistrationDate" TEXT,
    "PublicPhoneNumber" TEXT,
    "PoliticalPartyCommitteeName" TEXT,
    "CandidateStatus" TEXT,
    "OfficerHolderStatus" TEXT,
    "ElectionName" TEXT,
    "NumberofCandidates" TEXT,
    "OfficeId" TEXT,
    "ElectionId" TEXT,
    "DistrictId" TEXT,
    "ElectionCycleId" TEXT,
    "OfficeType" TEXT,
    "JurisdictionId" TEXT,
    "RegistrationId" TEXT,
    "TotalContributions" TEXT,
    "TotalExpenditures" TEXT,
    "FinanceStatus" TEXT,
    "RowNumber" TEXT,
    "TotalRows" TEXT,
    "UnregisteredCandidate" TEXT,
    "ChairPesonName" TEXT,
    "CommitteeSubtypeCode" TEXT,
    "CashOnHand" TEXT
);