DROP TABLE nm_expenditures_landing;

CREATE TABLE nm_expenditures_landing (
    org_id text,
    expenditure_amount text,
    expenditure_date text,
    payee_last_name text,
    payee_first_name text,
    payee_middle_name text,
    payee_prefix text,
    payee_suffix text,
    payee_address_1 text,
    payee_address_2 text,
    payee_city text,
    payee_state text,
    payee_zip_code text,
    description text,
    expenditure_id text,
    filed_date text,
    election text,
    report_name text,
    start_of_period text,
    end_of_period text,
    purpose text,
    expenditure_type text,
    reason text,
    stance text,
    report_entity_type text,
    committee_name text,
    candidate_last_name text,
    candidate_first_name text,
    candidate_middle_name text,
    candidate_prefix text,
    candidate_suffix text,
    amended text
);